### ISSUE TITLE
Seems to be broken on the new AndroidX runtime.

### ISSUE THREAD

**Issue by NaitorStudios** [Rhadamus/CTF-Perspective#1]
Gives this error:

Downloading https://services.gradle.org/distributions/gradle-6.7.1-all.zip
...........................................................................................................................................
Unzipping C:\Users\Tom Rasp\.gradle\wrapper\dists\gradle-6.7.1-all\2moa8rlfac5eqlcfgk98k0deb\gradle-6.7.1-all.zip to C:\Users\Tom Rasp\.gradle\wrapper\dists\gradle-6.7.1-all\2moa8rlfac5eqlcfgk98k0deb

Welcome to Gradle 6.7.1!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'AndBBF3.tmp', project ':app'
File C:\Users\Tom Rasp\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 30.0.2 in C:\Users\Tom Rasp\AppData\Local\Android\Sdk\licenses
License for package Android SDK Build-Tools 30.0.2 accepted.
Preparing "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)".
"Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" ready.
Installing Android SDK Build-Tools 30.0.2 in C:\Users\Tom Rasp\AppData\Local\Android\Sdk\build-tools\30.0.2
"Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" complete.
"Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" finished.
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:checkDebugAarMetadata
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:compressDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource
> Task :app:checkDebugDuplicateClasses
> Task :app:desugarDebugFileDependencies
> Task :app:mergeDebugJniLibFolders
> Task :app:mergeDebugResources
> Task :app:processDebugManifestForPackage
> Task :app:mergeExtDexDebug
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
> Task :app:mergeDebugNativeLibs

> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libES1Renderer.so, libES2Renderer.so, libES3Renderer.so, libRuntimeNative.so, libgdx.so.

> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac
C:\Users\Tom Rasp\AppData\Local\Temp\AndBBF3.tmp\app\src\main\java\Extensions\CRunPerspective.java:248: error: method renderImage in class GLRenderer cannot be applied to given types;
            GLRenderer.inst.renderImage(imageTexture, objX, objY, objWidth, objHeight, 0, 0);
                           ^
  required: ITexture,boolean,int,int,int,int,int,int
  found: CImage,int,int,int,int,int,int
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 30s
25 actionable tasks: 25 executed

**Comment by Rhadamus** [comment]
I've released a new version just now that hopefully fixes this.
https://github.com/Rhadamus/CTF-Perspective/releases/tag/mobile-v4
